### ISSUE TITLE
connect.showRequest is not a function

### ISSUE THREAD

**Issue by mmalmi** [uport-project/uport-js#44]
Readme instructs:
"In your front end use uport-connect to present it to your user either as a QR code or as a uport-button depending on whether they are on a desktop or mobile browser.

const connect = new uportconnect.Connect('app name')
connect.showRequest(requestToken).then(response => {
  // send response back to server
})"

Using the latest uport-connect from unpkg, I'm getting "connect.showRequest is not a function".

If requestToken -> showRequest flow is deprecated, what is the recommended way to request and verify user credentials server-side?

**Comment by MichalW** [comment]
@mmalmi Have you solved the problem? What I should use instead of `connect.showRequest`?

**Comment by MichalW** [comment]
@mmalmi I have managed this:
try this:
```
const connect = new uportconnect.Connect('app name')
const uri = `https://id.uport.me/me?requestToken=${requestToken}`;
const topic = connect.topicFactory('access_token');
connect.request({uri, topic}).then(response => {
    // send response back to server
});
```

**Comment by vleipnik-consensys** [comment]
@mmalmi thank you for your solution, this unblocked me as well. However what I'm seeing now is that QR code comes up, I allow it on my mobile phone, but then it neither resolves nor rejects the request promise, and the QR code remains up on the web app. Did you run into this by any chance?

**Comment by MichalW** [comment]
You should get "response", after allow on uPort application. 
You can first try out how it works in this example: https://github.com/uport-project/uport-js/blob/develop/tutorial/requestcredential.js

**Comment by oed** [comment]
@MichalW @vleipnik-consensys I think the reason is that you don't provide any callback url for the mobile app to respond to. This code should work:
```js
const connect = new uportconnect.Connect('app name')
const topic = connect.topicFactory('access_token');
const uri = `https://id.uport.me/me?requestToken=${encodeURIComponent(requestToken)}&callback_url=${encodeURIComponent(topic.url)}`
connect.request({uri, topic}).then(response => {
    // send response back to server
});
```

I also added the showRequest method in https://github.com/uport-project/uport-connect/pull/102

**Comment by vongohren** [comment]
Did you guys get past this issue, cause I'm experiencing it now. And solutions on your side does not seem to work.

**Comment by localredhead** [comment]
We will be updating our libs soon to address some of this.  Please keep an eye out for https://github.com/uport-project/uport-connect/pull/129

**Comment by martingronlund** [comment]
@localredhead what should one do currently?
