### ISSUE TITLE
Add HowTo for Apache HTTP-server

### ISSUE THREAD

**Issue by renne** [uport-project/uport-js#46]
Please add an [Apache HTTP-server](https://httpd.apache.org/) login-HowTo with example code as a showcase.

**Comment by oed** [comment]
I'm not sure what you are asking. Can you elaborate?

**Comment by renne** [comment]
Apache HTTPd is the most-widely used web-server on the internet. Allowing internet users to authenticate on websites provided by Apache HTTPd with uPort would promote uPort a lot.

I suggest to provide a step-by-step guide for Apache HTTPd administrators how to to configure uPort-authentication for users. That guide should address professional and non-professional administrators.

**Comment by oed** [comment]
Sounds cool. You could make it so that all uports which have a specific attestation will be granted access. 
I don't think this is a priority right now, but contributions are wellcome ;)

**Comment by localredhead** [comment]
Thank you for your feedback!  We are in the process of re-writing our tutorials and will take this into consideration.
