### ISSUE TITLE
uport website down? Cannot register app...

### ISSUE THREAD

**Issue by lazydino** [uport-project/uport-js#53]
https://developer.uport.me/myapps.html is not working ...

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by bdresser** [comment]
@lazydino it's working fine for me! 

could you provide a little more info about what you're seeing? what browser are you using? if you're trying to log in, what app version and device are you on?

**Comment by localredhead** [comment]
@lazydino Can you try running in incognito mode?

**Comment by localredhead** [comment]
Can you try going to appmanager.uport.me and let us know if you are able to register an app?

**Comment by lazydino** [comment]
I sign in with "Connect with uPort" option using uport mobile running in my galaxy s7 phone. I tried to create the app but I need to sign my app in phone? What do I do? I need to past my public-encryption key?

**Comment by simeonemanuilov** [comment]
Same problem. I am not able to register new app, already send ticket with more details to support,  but still no reply.

**Comment by bdresser** [comment]
@lazydino yes, the application identity you create through our app manager is linked to your personal uPort ID, so you'll need to sign from the mobile app to set up the app.

@simeonemanuilov could you provide some more details here on what you're seeing? device type, browser, details of the bug?

**Comment by localredhead** [comment]
We have not heard from you, so we are closing this.  If you still would like some help, please re-open it
