### ISSUE TITLE
Feature Request - Add support for other languages

### ISSUE THREAD

**Issue by filips123** [uport-project/uport-js#55]
Please make uPort avalible for other languages, like PHP, Python... This would be very useful, because many developers use other languages and they can't use uPort right now.
Also, add support for Native Application libraries.

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by zachferland** [comment]
@filips123 yeah we agree! we are currently working on breaking apart many of our libraries into smaller modules. One part of this is to help increasing understanding of our or protocol parts and to increase code readability, we hope these could then serve as a reference for implementations in other languages. We encourage others to help us build out libraries in other languages based on that reference, as we don't have any immediate plans for many other languages, anyone who is considering doing this should get in touch with us first. We are doing work though on supported libs for native apps!

**Comment by localredhead** [comment]
We definitely plan this in the future.  Thank you for the suggestion.

**Comment by filips123** [comment]
@localredhead @zachferland Is there any update? If not, this issue should be reopened or transfered to right repository to make attantion.

**Comment by localredhead** [comment]
@filips123 no update yet - but this is still on our radar.

**Comment by mirceanis** [comment]
@filips123 python and PHP is not yet available but native application support for Android and iOS is in development.

Check out
https://github.com/uport-project/uport-android-sdk
and
https://github.com/uport-project/uport-ios-sdk

A lot of other tooling had to be built before we could tackle the functionality of uport-credentials as a native library. This is only now being added to those SDKs.

**Comment by filips123** [comment]
Why was repository for [WordPress plugin](https://github.com/uport-project/uport-wordpress-plugin) archived? Will it not be supported?

**Comment by localredhead** [comment]
> Why was repository for [WordPress plugin](https://github.com/uport-project/uport-wordpress-plugin) archived? Will it not be supported?

Not by us for the foreseeable future.
