### ISSUE TITLE
Cannot get request-credentials tutorial to work

### ISSUE THREAD

**Issue by blinky3713** [uport-project/uport-js#57]
What is the current behavior?

The request-credentials tutorials are not working. I am proxying all http request from my iphone through my computer, and I can verify that by following the instructions with the latest version of the uport app, my phone does not attempt to hit the `POST /callback` endpoint after accepting 

you can read a detailed conversation starting here https://gitter.im/uport-project/Lobby?at=5ab0074af3f6d24c6891fa1d
 
follow any posts to or from @blinky3713 or Ilya Ostrovskiy @iostat

Please describe the behavior you are expecting

The phone should hit the callback endpoint with the requested credentials

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

follow the tutorials exactly, tweaking the desired credentials to be real, using any combination of name, ethereum address, or phone number

## Environment Details

I have tried every combination of running the server on a publicly accessible ip address or locally

## Failure Logs/Screenshots

Please include any relevant log snippets or files here.
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs, and link them here.
Do _NOT_ paste your full logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include logs!

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by localredhead** [comment]
Hi!  we've updated the tutorials!  please check out the `/examples` folder for an updated tutorial on requestCredentials.

**Comment by yungtiec** [comment]
I'm experiencing the same issue. I used the requestcrendentials code in the example folder and replaced the private key and address with mine. I never received the POST request at the /callback endpoint after I authorized the request in the uport app.
