### ISSUE TITLE
Node w/ experimental modules not recognizing uPort modules

### ISSUE THREAD

**Issue by jrgleason** [uport-project/uport-js#68]
## Current Behavior

Based on the documentation I should be able to import uport-js into a node project like this `import { Credentials, SimpleSigner } from 'uport'`. [link](https://github.com/uport-project/uport-js)

## What actually happens

```
import { Credentials, SimpleSigner } from 'uport';
         ^^^^^^^^^^^
SyntaxError: The requested module 'uport' does not provide an export named 'Credentials'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:89:21)
```

## Steps to Reproduce

1. `npm init` (with defaults)
2. `npm install --save express uport`
3. Create the following under index.**mjs**
```
import { Credentials, SimpleSigner } from 'uport';
import express from 'express';
static app = express();
app.get('/', function(req, res){
    let signer = this.signer = SimpleSigner("5acea265dcbf01355956b36f82793a13caf1be650bb74ca7a40da74b412d44b5");
    res.send(signer != null);
});
```
4. run `node --experimental-modules index.mjs`
5. You should see the error

## Environment Details

- OSX

- Node v11.0.0-pre

- uPort 0.6.2

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by jrgleason** [comment]
My mitigation didn't work FYI 

```
ReferenceError: signer is not defined
    at new UPortBase (file:///Users/jackiegleason/Code/secondave-private/webtask/uPort/uportBase.mjs:8:21)
```

**Comment by jrgleason** [comment]
Also 

```
import UPort from 'uport';
console.log(JSON.stringify(UPort));
```
Prints 

> {"JWT":{}}

and printing the SimpleSigner returns undefined.

**Comment by jrgleason** [comment]
I think the issue here is you are using babel for some things when you should be using Webpack.

For example, if you are using a browser with ES2017 built in why would you want to transpile down to ES2015? Now if a browser doesn't have a feature you need (say the 2019 spec) then it makes perfect sense to use Babel for that. However, when you are doing things like linting it should be done through the library that is used (eslint) without a intermediary. Webpack is way closer to that paradigm. 

It isn't just you guys though some of your dependencies have issues as well. It seems it is an issue with the entire React Community and probably comes down to cut and paste. I have had to patch a couple other libraries and I am working on a solution...

https://github.com/jrgleason/uport-js/tree/68

Let me know what you think, I am mainly worried about confirming that linting, etc are still configured/working right.

**Comment by jrgleason** [comment]
BTW I am trying to prove it but I think the main fix is adding this to the index.js...

    export { Credentials, SimpleSigner, Contract, ContractFactory, JWT }

But I figure that is redundant and there has to be a better way.

**Comment by KamesCG** [comment]
@jrgleason Thanks for reporting this! I will take a look at what might be causing this issue.

**Comment by jrgleason** [comment]
Maybe thisish? 

Object.defineProperty (exports, "__esModule", {
   value: true
});
exports.default = MyDefaultExportedClass;

https://stackoverflow.com/questions/43859231/babel-js-using-import-and-export-not-working

**Comment by localredhead** [comment]
Sorry @jrgleason but we are not able to support using the `--experimental-modules` flag at this time.
