### ISSUE TITLE
Links to further documentation in README are broken

### ISSUE THREAD

**Issue by canadaduane** [uport-project/uport-js#83]
Clicking any of the links in the `What is uPort Identity?` section of the README leads to 404s:

```
Sign JWTs (JSON Web Tokens)
    Authenticate themselves to a third party
    Disclose private information about themselves
Receive requests for disclosure about themselves
Receive and store signed third party verifications about themselves
Sign Ethereum transactions
```

It looks like it's anticipating directories such as `develop/messages` and `develop/flow` to exist, with markdown doc files within. These files seem to be absent, however, when casually browsing via the github web interface.

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by localredhead** [comment]
Links updated

**Comment by canadaduane** [comment]
Excellent, thanks!
