### ISSUE TITLE
As a developer, I would like documentation that would allow functional communication between a uport.js server & uport-connect client

### ISSUE THREAD

**Issue by RyRy79261** [uport-project/uport-js#96]
# Current Behavior
Following the documentation for uport.js to uport-connect client instance includes a function which does not exist in uport-connect package

# Expected Behavior
Documentation for a prominent identity system to be maintained effectively in line with ecosystem for further adoption

# Failure Information (for bugs)
```const connect = new uportconnect.Connect('app name')
connect.showRequest(requestToken).then(response => {
  // send response back to server
})``` 

showRequest does not exist in uport-connect.

**Comment by RyRy79261** [comment]
https://github.com/uport-project/uport-js/pull/94

Work is being done on the documentation however this is being ignored

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by localredhead** [comment]
Hi @RyRy79261 ,

I'm sorry for your frustration.  It appears we intended to release this functionality and we forgot to redact it when we decided to hold off releasing that feature.  

Thank you for pointing this out.  We'll remedy this ASAP.

**Comment by RyRy79261** [comment]
Hi @localredhead 

Thanks for the reply, however I've looked through several PR's and looked through the history of a couple files and this issue has been prevalent for a while now.

What alternative is available?

**Comment by localredhead** [comment]
The reference to the missing connect method was redacted in #94 

We have a similar concept with uport-connect in our next major release for DID support.   https://github.com/uport-project/uport-connect/blob/did-major/src/Connect.js#L199  you'll note that Connect's send() calls the appropriate transport method.  

FYI: The reference doc for send:  https://github.com/uport-project/uport-connect/blob/did-major/docs/reference/index.md#connectsendrequest-id-opts

If you cannot wait for this to be released you can use uport-transports in a similar fashion as the `send()` method.  https://github.com/uport-project/uport-transports#-quick-start  

Please note that the transports library was born out of an architecture overhaul that is part of the next major release.    You can use transports now, however you'll note references to things in the README like `uport-credentials`.   FYI **Uport-JS** will be renamed to `uport-credentials` once this major release is published so you can assume credentials means uport-js.

If you haven't seen our developer documentation site we have for the current uport-connect details about how to use the connect library to display a QR:  https://developer.uport.me/uport-connect/guides/usage#default-qr-flow and page on using connect's `requestCredentials()` https://developer.uport.me/requestcredentials.  The diagrams on this last link should hopefully help understand the interaction between the mobile client and browser/dapp .

In addition to that we have server-side documentation for the current uport-js here: 
 https://developer.uport.me/uport-js/guides/server-side-credentials-example

I see that you also commented in our riot channel @ chat.uport.me - I will follow up with you there.
